### PR TITLE
Remove single reaction

### LINKED ISSUE #8: No handler error returned when bot reacts to it's own message.
Error: 
`2020-09-14T21:33:35.632Z  WARN >> No handlers found able to handle hook 'messageReactionAdd' with args: [{"messageID":"753003103363792947","me":true,"users":[],"count":null},{"id":"732968902275104859","username":"Jarvis","bot":true,"discriminator":"8552","avatar":"3ba08b477f63e131b4bdce9f30fe42a0","lastMessageChannelID":"753001880812257373","verified":true,"mfaEnabled":true,"flags":0,"createdTimestamp":1594823804206,"defaultAvatarURL":"https://cdn.discordapp.com/embed/avatars/2.png","tag":"Jarvis#8552","avatarURL":"https://cdn.discordapp.com/avatars/732968902275104859/3ba08b477f63e131b4bdce9f30fe42a0.webp","displayAvatarURL":"https://cdn.discordapp.com/avatars/732968902275104859/3ba08b477f63e131b4bdce9f30fe42a0.webp"}]
`
Discussed in discord, bot is reacting to it's own message and causing this error.

### PR DESCRIPTION
**Pull request by gavinvangent**
This code change will have the added reaction removed when the user requests training, rather than removing all reactions and then re-adding a single reaction.

This was intended to resolve https://github.com/accbh/discordbot/issues/8 but now an warning was being logged for not handling the removal of the single reaction.

A CancelTrainingRequestHandler was added to avoid this message from being logged.

Many unit test updates to boot

### CODE REVIEW

File: src/events/message-reaction-add/handlers/request-training.ts [hunk 1]
```diff
@@ -65,7 +64,7 @@ export class RequestTrainingHandler implements EventHandler {
                     return;
                 }
 
-                const clickableUrl = `${this.calendarUrl}${date.format('YYYYMMDD')}T100000Z%2F${date.format('YYYYMMDD')}T220000Z`; 
+                const clickableUrl = `${this.calendarUrl}${date.format('YYYYMMDD')}T100000Z%2F${date.format('YYYYMMDD')}T220000Z`;
```
Comment (liamdp) [inline src/events/message-reaction-add/handlers/request-training.ts:67]: maybe we could name this something more descriptive... such as googleCalLink or clickableGoogleCalLink?

File: src/lib/discord-helpers.ts [hunk 2]
```diff
@@ -1,51 +1,58 @@
...
         .setDescription(message);
 };
 
-export const sendMessageToUser = async function(header: string, message: string, user: User | PartialUser): Promise<void> {
-    // Should we be sending the bot's avatar instead?
-    const embeddedMessage = constructEmbeddedMessage(header, message, user.avatarURL());
-    await user.send(embeddedMessage);
+export const sendMessageToUser = async (header: string, message: string, user: User | PartialUser): Promise<void> => {
+    await factory.defaultRetry<Message>(() => {
+        // Should we be sending the bot's avatar instead?
```
Comment (liamdp) [inline src/lib/discord-helpers.ts:43]: agreed, lets send the bot's avatar when talking to the user in DMs, but running the check command should return the user's avatar

**Review by liamdln — COMMENTED** [review]
I've left two comments: Changing the variable name of the Google Calendar link and the avatar shown in DMs, do you agree with what I have suggested?

File: src/events/message-reaction-add/handlers/request-training.ts (hunk 1 above)
Comment (gavinvangent) [reply src/events/message-reaction-add/handlers/request-training.ts:67]: When I named this, I explicitly tried to avoid being specific to a calendar, like google ... If the user sets the calendarUrl to a nonGoogle url, this would no longer be a google url.

That said, the generated href is probably specific to Google, but it could work with other calendars too. We should introduce calendar enums (Google, Outlook, etc) and then based on the enum, generate a link ... but I didn't see importance in this yet

File: src/lib/discord-helpers.ts (hunk 2 above)
Comment (gavinvangent) [reply src/lib/discord-helpers.ts:43]: From all my testing, this only ever ends up using the bot's avatar .. Not really sure what changing this url does, but this is code was pre-existing my arrival ... We can add an issue to investigate

File: src/events/message-reaction-add/handlers/request-training.ts (hunk 1 above)
Comment (liamdp) [reply src/events/message-reaction-add/handlers/request-training.ts:67]: I see what you mean, I suppose `clickableUrl` followed by an assignment of `calendarUrl` is enough for someone to understand what's going on.
I like that idea, but as you said, probably better for later down the road.

File: src/lib/discord-helpers.ts (hunk 2 above)
Comment (liamdp) [reply src/lib/discord-helpers.ts:43]: If you look at a picture of the embedded section, there is an avatar at the top left. The avatar isn't needed but can sometimes having the avatar makes the styling nicer, maybe for sending DMs we don't need an avatar at all, but just the message. Keeping the avatar on a `¬check` command I think is a must, it helps identify the user we are checking. What do you think about removing the avatar from direct message communications all together?

Comment (gavinvangent) [reply src/lib/discord-helpers.ts:43]: Oh yes, I see what you mean.

When sending a message to a channel, this is what you see:

image

When the bot messages you direct, you get:

image

Maybe embeddedMessages in messages direct to the user aren't the right option?

Comment (liamdp) [reply src/lib/discord-helpers.ts:43]: Agreed, I will make this a separate issue as this probably isn't the best place to discuss it

**Review by liamdln — APPROVED** [review]
all looks good, thanks Gavin
